### ISSUE TITLE
Can't run app: SECRET_KEY settings must not be empty

### ISSUE THREAD

**Issue by iameo** [hngi/spreadsheet-parser#11]
Reproducing the issue:

- cd into project directory (the same base as manage.py)
- python manage.py runserver

output:     _raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty._

I figured you have the key hidden.

**Comment by damiso15** [comment]
The secret key is confidential and can only be shared to those in the team
