### ISSUE TITLE
Create a view function to extract required data from MDA expenses 

### ISSUE THREAD

**Issue by payn33** [hngi/spreadsheet-parser#41]

**Comment by cornzyblack** [comment]
I'll handle this.

**Comment by cornzyblack** [comment]
Hi, @payn33 trust you are doing well, do you know if there is any documentation somewhere, where I can find the expected data to be extracted from MDA expenses? Like the necessary column names for the task?

Thanks

**Comment by NwokoyeChigozie** [comment]
I will work on it

**Comment by NwokoyeChigozie** [comment]
Done
